# Hotel Booking Cancellation Analysis
---

## Import libraries

In [1]:
import pandas as pd
pd.set_option('display.max_columns',40)
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

import warnings
warnings.filterwarnings('ignore')

## Load the data

In [2]:
# Load the dataset
df = pd.read_csv(r"C:\Users\Bhawna\OneDrive\Desktop\Hotel booking cancellation analysis\hotel_bookings.csv")

# Shape of the dataset
print(f'Shape of the dataset: {df.shape}\n')
# display top 5 rows
display(df.head())

Shape of the dataset: (119390, 32)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

## Checking null values, datatypes and unique values

In [3]:
# quick check dataframe
check_df = pd.DataFrame({
    'Features': df.columns,
    'Null Values': [df[c].isnull().sum() for c in df.columns],
    'Data Type': [df[c].dtypes for c in df.columns],
    'Unique Values': [df[c].nunique() for c in df.columns]
})

# display check_df with sorting
display(check_df.sort_values('Null Values', ascending=False))

                          Features  Null Values Data Type  Unique Values
24                         company       112593   float64            352
23                           agent        16340   float64            333
13                         country          488    object            177
10                        children            4   float64              5
4               arrival_date_month            0    object             12
5         arrival_date_week_number            0     int64             53
0                            hotel            0    object              2
1                      is_canceled            0     int64              2
7          stays_in_weekend_nights            0     int64             17
6        arrival_date_day_of_month            0     int64             31
9                           adults            0     int64             14
8             stays_in_week_nights            0     int64             35
11                          babies            0     int64              5
12                            meal            0    object              5
2                        lead_time            0     int64            479
3                arrival_date_year            0     int64              3
15            distribution_channel            0    object              5
14                  market_segment            0    object              8
18  previous_bookings_not_canceled            0     int64             73
16               is_repeated_guest            0     int64              2
19              reserved_room_type            0    object             10
20              assigned_room_type            0    object             12
21                 booking_changes            0     int64             21
17          previous_cancellations            0     int64             15
22                    deposit_type            0    object              3
25            days_in_waiting_list            0     int64            128
26                   customer_type            0    object              4
27                             adr            0   float64           8879
28     required_car_parking_spaces            0     int64              5
29       total_of_special_requests            0     int64              6
30              reservation_status            0    object              3
31         reservation_status_date            0    object            926

## Data Cleaning

In [4]:
# Drop company feature because it has almost each row blank and
# it won't create much impact on our project
df.drop(['company'], axis=1, inplace=True)

In [5]:
# For agent feature, first i will fill null values with 0
# then i will change its data type float to int

# Fill null values
df['agent'] = df['agent'].fillna(0)

# Change its datatype
df['agent'] = df['agent'].astype(int)

In [6]:
# For country, i will fill null values with unknown country
# because if i assign it with mode then it may become bias

# Fill null values
df['country'] = df['country'].fillna('Unknown')

In [8]:
# For children, i will fill null values with 0
# and then change its datatype float to int

# Fill null values
df['children'] = df['children'].fillna(0)

# Change its datatype
df['children'] = df['children'].astype(int)